# Use the official Python base image
FROM quay.io/modh/runtime-images:runtime-datascience-ubi9-python-3.9-2023a-20240712-ff9e51d	

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the dependencies specified in the requirements file
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Specify the command to run the Python script
CMD ["python", "poller.py"]
