{{if .Values.namespaces }}
{{ range $namespace := .Values.namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}-appset
  namespace: mlops-gitops
  labels:
    app.kubernetes.io/instance: {{ .name }}-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/ckavili/model-registry-poller.git
      revision: main
      files:
      - path: gitops-config/{{ .name }}/**/config.yaml
  template:
    metadata:
      name: {{` '{{ .name }}-{{ .namespace }}' `}}
      labels:
        app.kubernetes.io/instance: {{` '{{ .name }}-{{ .namespace }}' `}}
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: {{` '{{ .namespace }}' `}}
      project: default
      sources:
        - helm:
            valueFiles:
              - "$app-values/gitops-config/{{`{{ .namespace }}/{{ .name }}`}}/config.yaml"
            # values: |
            #   storage_uri: {{` '{{ .storage_uri }}' `}}
          path: model-deployment
          repoURL: 'https://github.com/ckavili/model-registry-poller.git'
          targetRevision: HEAD
        - path: .
          ref: app-values
          repoURL: "https://github.com/ckavili/model-registry-poller.git"
          targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
{{- end }}
{{- end }}
