{{if .Values.namespaces }}
{{ range $namespace := .Values.namespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .name }}-mlops-rolebinding
  namespace: {{ .name }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: MLOps_Admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .name }}-mlops-sa-rb
  namespace: {{ .name }}
subjects:
  - kind: ServiceAccount
    name: mlops-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}
{{- end }}
